# configs/predict_config.yaml
model:
    in_channels: 3
    num_classes: 2
    base_channel: 32
    depth: 5
    use_transformer: true
    transformer_heads: 8
    transformer_dim_head: 64
    transformer_dropout: 0.1
    use_fpn: true
    fpn_channels: 256
    deep_supervision: false

prediction:
    weights_path: "experiments/mineops_change_detection_latest/checkpoints/best_model.pt"
    output_dir: "predictions"
    batch_size: 8
    parallel: false
    save_probabilities: true

data:
    # Explicit paths to test data files
    xA_path: "/data/02_model_input/mineops_cd_xA.npy"
    xB_path: "/data/02_model_input/mineops_cd_xB.npy"
    normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
