# configs/train_config.yaml
model:
    in_channels: 3
    num_classes: 2
    base_channel: 32
    depth: 5
    use_transformer: true
    transformer_heads: 8
    transformer_dim_head: 64
    transformer_dropout: 0.1
    use_fpn: true
    fpn_channels: 256
    deep_supervision: true

training:
    seed: 42
    num_epochs: 100
    batch_size: 16
    learning_rate: 0.001
    weight_decay: 0.01
    gradient_accumulation_steps: 1
    max_grad_norm: 1.0
    mixed_precision: true
    parallel: false

data:
    # Explicit paths to data files
    xA_path: "/data/02_model_input/mineops_cd_xA.npy"
    xB_path: "/data/02_model_input/mineops_cd_xB.npy"
    mask_path: "/data/02_model_input/mineops_cd_y.npy"
    val_split: 0.2
    normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

output:
    output_dir: "experiments"
    experiment_name: "mineops_change_detection"
