# configs/train_config.yaml
model:
    in_channels: 6
    num_classes: 1
    base_channel: 64
    depth: 6

training:
    seed: 42
    num_epochs: 1500
    batch_size: 6
    learning_rate: 0.00005
    weight_decay: 0.0002
    gradient_accumulation_steps: 4
    max_grad_norm: 1.0
    mixed_precision: false
    parallel: false
    eval_frequency: 5

loss:
    focal_weight: 0.4
    dice_weight: 0.6
    focal_alpha: 0.75
    focal_gamma: 3.0

data:
    # Explicit paths to data files
    xA_path: "src/data/02_model_input/mineops_cd_xA.npy"
    xB_path: "src/data/02_model_input/mineops_cd_xB.npy"
    mask_path: "src/data/02_model_input/mineops_cd_y.npy"
    val_split: 0.1
    normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

output:
    output_dir: "experiments"
    experiment_name: "mineops_change_detection"
