# configs/train_config.yaml
model:
    in_channels: 6
    num_classes: 1
    base_channel: 32
    depth: 5
    use_transformer: false
    transformer_heads: 8
    transformer_dim_head: 64
    transformer_dropout: 0.1
    use_fpn: false
    fpn_channels: 64
    deep_supervision: true

training:
    seed: 42
    num_epochs: 50
    batch_size: 2
    learning_rate: 0.001
    weight_decay: 0.01
    gradient_accumulation_steps: 4
    max_grad_norm: 1.0
    mixed_precision: false
    parallel: false
    eval_frequency: 5

data:
    # Explicit paths to data files
    xA_path: "src/data/02_model_input/mineops_cd_xA.npy"
    xB_path: "src/data/02_model_input/mineops_cd_xB.npy"
    mask_path: "src/data/02_model_input/mineops_cd_y.npy"
    val_split: 0.2
    normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

output:
    output_dir: "experiments"
    experiment_name: "mineops_change_detection"
